server:
  port: 8081

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/itcast?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: root
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

mybatis:
  typeAliasesPackage: com.demo.pojo
  mapperLocations: classpath:mappers/*.xml

logging:
  level: 
    cn.tedu.mapper: debug

